#!/bin/bash
# Devilbox helper. Starts / restarts containers

if [ "$1" != '' ]; then
	cd ~/projects/devilbox || exit

	case "$1" in
		stop )
		docker-compose stop
		docker-compose rm -f
		;;
		restart|start )
		docker-compose stop
		docker-compose rm -f
		docker-compose up -d httpd mysql php 
		;;
	esac
else
	echo $"Usage: $0 {start|stop|restart}"
fi
exit 1
